name: Koska Panda
favicon: null
layout_spectrum: 0.72609
typography_spectrum: 0.3039521479513496
title: 'WWF:n nuorten wap-sivut'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cddff1'
    - '#585953'
    - '#212832'
    - '#880010'
    - '#af440d'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
